SUDO-265 Adds RHEL/CentOS Support & Pre-Checks (#19)
* add boxes and configure hostmanager to make local testing easier

* better handling when the event log file is unavailable

* add system-requirements as json

* add --ignore-existing flag to suppress failed checks on existing installations

* add in basic pre-check for supported operating systems

* return 1 if existing docker-compose files are found

* add some debug logging when copying the cli to user PATH

* added support for checking that basic packages are installed

* adding in support for installing system packages across apt/yum systems

* fix plextrac user profile/bashrc setup for non-standard installation directories

* added more checks and tweaks for RHEL and CentOS so that it can run and install

* fixed issue with older tee and openssl packages

* use absolute path for docker-compose

Co-authored-by: Mike Morgan <mmorgan@plextrac.com>
Co-authored-by: mmorgan-pt <99763568+mmorgan-pt@users.noreply.github.com>

diff --git a/src/plextrac b/src/plextrac
--- a/src/plextrac
+++ b/src/plextrac
@@ -36,6 +36,7 @@ function cleanup() {
     log "Try running with '-v' for verbose output for more details"
   fi
 
+  trap - EXIT  # prevent calling cleanup again on exit
   exit $status_code
 }
 
@@ -122,6 +123,16 @@ function main() {
         ;;
       "-y" | "--assume-yes")
         ASSUME_YES=true
+        shift
+        ;;
+      # only used for mod_check
+      "--pre" | "--preinstall")
+        DO_PREINSTALL_CHECKS=1
+        shift
+        ;;
+      # skip checks for existing installation, mostly for doing a migration
+      "--ignore-existing")
+        IGNORE_EXISTING_INSTALLATION=1
         shift
         ;;
       "--install-dir" | "--plextrac-home")
@@ -265,19 +276,6 @@ function mod_start() {
   done
   echo -n >&2 "${RESET}"
   msg " Done"
-}
-
-function mod_check() {
-  title "Checking Local Configuration"
-  requires_user_plextrac
-  info "Checking Docker Compose Config"
-  compose_client config -q && info "Config check passed"
-  pending=`composeConfigNeedsUpdated || true`
-  if [ "$pending" != "" ]; then
-    error "Pending Changes:"
-    msg "    %s\n" "$pending"
-  fi
-  VALIDATION_ONLY=1 configure_couchbase_users
 }
 
 function mod_autofix() {
